import $ from 'jquery'
import Head from "next/head";
import Image from "next/image";
import React, { useEffect, CSSProperties } from "react";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import SideBar from "../components/Sidebar";
import TopBar from "../components/TopBar";
import { useRouter } from 'next/router'
import { useAuth } from '../hooks/AuthHook';
import { Loading } from '../components/Loading';
import Card  from '../components/Card';

export default function Home({children, href}: any) {
  const [isLoading , setIsLoading] = React.useState(false)
  const router = useRouter()

  useEffect(() => {
    if (typeof window !== 'undefined') {
      // DashBoard <> Charts
      setIsLoading(true)
      window['ApexCharts'] = require('../public/plugins/apexchart/apexcharts.min.js');
      require('../public/plugins/apexchart/chart-data.js')
    }
  }, []);

  const elemWidth: CSSProperties = {
      width: "75%"
  }

  const secElemWidth: CSSProperties = {
    width: "65%"
  }

    const thirdElemWidth: CSSProperties = {
      width: "75%"
  }

  const fourthElemWidth: CSSProperties = {
    width: "65%"
  }

  const styles = {
    elemWidth,
    secElemWidth,
    thirdElemWidth,
    fourthElemWidth
  }

  return (
    <>
      <Head>
        <title>Isiro Accounting system</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/isiro_logo.png" />
      </Head>
      <main>  
      { isLoading &&
        <div className="main-wrapper">
          <SideBar />
          <TopBar />
          <div className="page-wrapper">
            <div className="content container-fluid">
              <div className="row">
                <div className="col-xl-3 col-sm-6 col-12">
                  <div className="card">
                    <div className="card-body">
                      <div className="dash-widget-header">
                        <span className="dash-widget-icon bg-1">
                          <i className="fas fa-dollar-sign"></i>
                        </span>
                        <div className="dash-count">
                          <div className="dash-title">Amount Due</div>
                          <div className="dash-counts">
                            <p>1,642</p>
                          </div>
                        </div>
                      </div>
                      <div className="progress progress-sm mt-3">
                        <div
                          className="progress-bar bg-5"
                          style={styles.elemWidth}
                        ></div>
                      </div>
                      <p className="text-muted mt-3 mb-0">
                        <span className="text-danger me-1">
                          <i className="fas fa-arrow-down me-1"></i>1.15%
                        </span>{" "}
                        since last week
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-xl-3 col-sm-6 col-12">
                  <div className="card">
                    <div className="card-body">
                      <div className="dash-widget-header">
                        <span className="dash-widget-icon bg-2">
                          <i className="fas fa-users"></i>
                        </span>
                        <div className="dash-count">
                          <div className="dash-title">Customers</div>
                          <div className="dash-counts">
                            <p>3,642</p>
                          </div>
                        </div>
                      </div>
                      <div className="progress progress-sm mt-3">
                        <div
                          className="progress-bar bg-6"                   
                          style={styles.secElemWidth}
                        ></div>
                      </div>
                      <p className="text-muted mt-3 mb-0">
                        <span className="text-success me-1">
                          <i className="fas fa-arrow-up me-1"></i>2.37%
                        </span>{" "}
                        since last week
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-xl-3 col-sm-6 col-12">
                  <div className="card">
                    <div className="card-body">
                      <div className="dash-widget-header">
                        <span className="dash-widget-icon bg-3">
                          <i className="fas fa-file-alt"></i>
                        </span>
                        <div className="dash-count">
                          <div className="dash-title">Invoices</div>
                          <div className="dash-counts">
                            <p>1,041</p>
                          </div>
                        </div>
                      </div>
                      <div className="progress progress-sm mt-3">
                        <div
                          className="progress-bar bg-7"
                          style={styles.thirdElemWidth}
                        ></div>
                      </div>
                      <p className="text-muted mt-3 mb-0">
                        <span className="text-success me-1">
                          <i className="fas fa-arrow-up me-1"></i>3.77%
                        </span>{" "}
                        since last week
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-xl-3 col-sm-6 col-12">
                  <div className="card">
                    <div className="card-body">
                      <div className="dash-widget-header">
                        <span className="dash-widget-icon bg-4">
                          <i className="far fa-file"></i>
                        </span>
                        <div className="dash-count">
                          <div className="dash-title">Estimates</div>
                          <div className="dash-counts">
                            <p>2,150</p>
                          </div>
                        </div>
                      </div>
                      <div className="progress progress-sm mt-3">
                        <div
                          className="progress-bar bg-8"
                          style={fourthElemWidth}
                        ></div>
                      </div>
                      <p className="text-muted mt-3 mb-0">
                        <span className="text-danger me-1">
                          <i className="fas fa-arrow-down me-1"></i>8.68%
                        </span>{" "}
                        since last week
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="row">
                <div className="col-xl-7 d-flex">
                  <div className="card flex-fill">
                    <div className="card-header">
                      <div className="d-flex justify-content-between align-items-center">
                        <h5 className="card-title">Sales Analytics</h5>
      
                        <div className="dropdown">
                          <button
                            className="btn btn-white btn-sm dropdown-toggle"
                            type="button"
                            id="dropdownMenuButton"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                          >
                            Monthly
                          </button>
                          <ul
                            className="dropdown-menu"
                            aria-labelledby="dropdownMenuButton"
                          >
                            <li>
                              <a
                                href="#;"
                                className="dropdown-item"
                              >
                                Weekly
                              </a>
                            </li>
                            <li>
                              <a
                                href="#;"
                                className="dropdown-item"
                              >
                                Monthly
                              </a>
                            </li>
                            <li>
                              <a
                                href="#;"
                                className="dropdown-item"
                              >
                                Yearly
                              </a>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div className="card-body">
                      <div className="d-flex align-items-center justify-content-between flex-wrap flex-md-nowrap">
                        <div className="w-md-100 d-flex align-items-center mb-3 flex-wrap flex-md-nowrap">
                          <div>
                            <span>Total Sales</span>
                            <p className="h3 text-primary me-5">$1000</p>
                          </div>
                          <div>
                            <span>Receipts</span>
                            <p className="h3 text-success me-5">$1000</p>
                          </div>
                          <div>
                            <span>Expenses</span>
                            <p className="h3 text-danger me-5">$300</p>
                          </div>
                          <div>
                            <span>Earnings</span>
                            <p className="h3 text-dark me-5">$700</p>
                          </div>
                        </div>
                      </div>

                      <div id="sales_chart"></div>
                    </div>
                  </div>
                </div>
                <div className="col-xl-5 d-flex">
                  <div className="card flex-fill">
                    <div className="card-header">
                      <div className="d-flex justify-content-between align-items-center">
                        <h5 className="card-title">Invoice Analytics</h5>

                        <div className="dropdown">
                          <button
                            className="btn btn-white btn-sm dropdown-toggle"
                            type="button"
                            id="dropdownMenuButton1"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                          >
                            Monthly
                          </button>
                          <ul
                            className="dropdown-menu"
                            aria-labelledby="dropdownMenuButton1"
                          >
                            <li>
                              <a
                                href="#;"
                                className="dropdown-item"
                              >
                                Weekly
                              </a>
                            </li>
                            <li>
                              <a
                                href="#;"
                                className="dropdown-item"
                              >
                                Monthly
                              </a>
                            </li>
                            <li>
                              <a
                                href="#;"
                                className="dropdown-item"
                              >
                                Yearly
                              </a>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div className="card-body">
                      <div id="invoice_chart"></div>
                      <div className="text-center text-muted">
                        <div className="row">
                          <div className="col-4">
                            <div className="mt-4">
                              <p className="mb-2 text-truncate">
                                <i className="fas fa-circle text-primary me-1"></i>{" "}
                                Invoiced
                              </p>
                              <h5>$ 2,132</h5>
                            </div>
                          </div>
                          <div className="col-4">
                            <div className="mt-4">
                              <p className="mb-2 text-truncate">
                                <i className="fas fa-circle text-success me-1"></i>{" "}
                                Received
                              </p>
                              <h5>$ 1,763</h5>
                            </div>
                          </div>
                          <div className="col-4">
                            <div className="mt-4">
                              <p className="mb-2 text-truncate">
                                <i className="fas fa-circle text-danger me-1"></i>{" "}
                                Pending
                              </p>
                              <h5>$ 973</h5>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="row">
                  <Card />
                  <Card />
              </div>
            </div>
          </div>
        </div> }
        { ! isLoading && <Loading hasBackground={true} /> }
      </main>
    </>
  );
}
